package entity;


import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;




/**
 * Regions generated by hbm2java
 */
@Entity(name="regions")
@Table(name = "REGIONS", schema = "HR")
public class Regions implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2575595129155389274L;
	private BigDecimal regionId;
	private String regionName;

	public Regions() {
	}

	public Regions(BigDecimal regionId) {
		this.regionId = regionId;
	}

	public Regions(BigDecimal regionId, String regionName) {
		this.regionId = regionId;
		this.regionName = regionName;
	}

	@Id

	@Column(name = "REGION_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getRegionId() {
		return this.regionId;
	}

	public void setRegionId(BigDecimal regionId) {
		this.regionId = regionId;
	}

	@Column(name = "REGION_NAME", length = 25)
	public String getRegionName() {
		return this.regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}
	
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return this.regionName + " " +this.regionId.toString();
	}

}
